made more c++ like
dmach/libdnf-cpp-proof-of-concept pull request #2
Opened 2017-10-27 11:00 UTC by mhatina

Changes:
 * one class per one .cpp/.hpp
 * not using `using namespace std;` in header files
 * attributes are at the bottom of the class and always private or protected (never public)
 * constructors should be marked as `= default` or erased, if they do nothing

Suggestions:
 * Use camelCase for naming (classes are already named this way)

2017-10-29 16:05 UTC, dmach requested changes

2017-10-29 16:05 UTC, dmach commented on CMakeLists.txt
> +    set (PYTHON_DESIRED "2")
Let's make Python 3 default

2017-10-29 16:05 UTC, dmach commented on libdnf/CMakeLists.txt
> +        rpmpackage.hpp
If we're going to split sources and headers this way, we need to move them into subdirs.
We should consider creating top-level header files for easier includes.

2017-10-29 16:05 UTC, dmach commented on libdnf/package.hpp
> -using namespace std;
We should really consider removing 'using namespace std' in header files. +1

2017-10-29 16:05 UTC, dmach commented on libdnf/repo.cpp
> +    this->repoid = value;
I'd prefer underscore for private and protected members, especially when used without this-> (as jrohel suggested).

2017-10-29 16:05 UTC, dmach commented on libdnf/repo.cpp
> +const string &Repo::get_repoid() const {
what the second const mean?

2017-10-30 07:02 UTC, mhatina commented on CMakeLists.txt
> +    set (PYTHON_DESIRED "2")
Agree. It was copy-pasted from dnf.

2017-10-30 07:02 UTC, mhatina commented on libdnf/CMakeLists.txt
> +        rpmpackage.hpp
Agree.

2017-10-30 07:03 UTC, mhatina commented on libdnf/repo.cpp
> +const string &Repo::get_repoid() const {
Second const marks function. It means it won't and it can't change the class.

2017-10-30 07:16 UTC, mhatina commented on libdnf/repo.cpp
> +    this->repoid = value;
Strongly disagree. Classes should be small enough so the attributes are unique and easily distinguishable. If the classes are so big that there is need of `_`, then those classes are violating Single responsibility principle. Also there are lots of IDEs that highlight the attributes.

Besides, you will quickly learn to ignore the `_` to see just a name of attribute and `_` will become just unseen clutter that we don't want.

2017-10-30 07:29 UTC, mhatina commented on libdnf/repo.cpp
> +    this->repoid = value;
Really bad example I found googling:
```
class A {
    void foo(int age_) { // parameter
        int age = 18; // local scope
        if (age_ > age) {
            cout << legal << endl;
            _age = age_;
        }
    }
    int _age; // member
};
```

After few go-throughs, you will only see 5 `age`s, that looks the same, but are different. And if you comment, that you can see the `_` (of course you are focusing on seeing the `_`), try to read the code in few days without thinking what this is about and try to understand what the code does. I guarantee that you will not see the `_`.

2017-10-30 20:38 UTC, dmach commented
It doesn't compile.
Can you also incorporate "lost changes because of rebase" into other commits?

2017-11-02 08:45 UTC, merged